<html>
<?php include "head.phtml"; ?>    
<body>
    <div style="width:100%;background: #fff">
        
        <div class='content' style='height:100vh'>

            <div class='p404_wrapper'>
                <p class='p404_code'>404</p>
                <p class='p404_msg'>Запрашиваемая страница не найдена!</p>
                <p>Возможно она была перенесена или больше не существует!</p>
                <p>Начните с <a href='/'>главной страницы</a></p>
            </div>                
            
        </div>
        
    </div>
</body>
</html>